export type BigClass = keyof typeof BigEnum;
export type SmallClass = keyof typeof SmallEnum;
export type MiddleClass = keyof typeof MiddleEnum;

enum SmallEnum {
  HUMANITIES,
  SOCIAL,
  NATURAL,
  SPORTS_HEALTH,

  ENGLISH,
  CHINESE,
  KOREAN,
  JAPANESE,

  PRACTICE_SKILLS,
  CAREER_DEVELOPMENT,

  BASIC_SPECIAL_TRAINING,

  BASIC_INFORMATION,
  BUSINESS_ACCOUNTING,

  UPGRADE_INFORMATION,

  NETWORK,
  DATA_SCIENCE,
  ACCOUNTING,
  BUSINESS,
  INTERNATIONAL_BUSINESS,

  SEMINAR,

  SPECIALIZED_SPECIAL_TRAINING,
}

enum MiddleEnum {
  GENERAL_EDUCATION,
  LANGUAGE,
  CAREER_DEVELOPMENT,
  BASIC_SPECIAL_TRAINING,

  SPECIALIZED_BASIS,
  SPECIALIZED_UPGRADE,
  SPECIALIZED_PRACTICAL,
  SEMINAR,
  SPECIALIZED_SPECIAL_TRAINING,
}

enum BigEnum {
  BASIC_GENERAL,
  SPECIALIZED_EDUCATION,
}
